valor = input('digite algo:')
print('o tipo primitivo desse valor é:{}'.format(type(valor)))
print('só tem espaços ??:{}'.format(valor.isspace()))
print('é um número ??:{}'.format(valor.isnumeric()))
print('é alfabetico ??:{}'.format(valor.isalpha()))
print('é alfanumercio ??:{}'.format(valor.isalnum()))
print('está em maiusculas ??:{}'.format(valor.isupper()))
print('está em minusculo ??:{}'.format(valor.islower()))
print('esta captalizada ??:{}'.format(valor.istitle()))